export const svModels = [
  {
    path: "/models/sv/CassGrandmaBread.glb",
    name: "Grandma’s Ceramic Breadholder",
    cardNum: "#2301",
    poetic:
      "After my gram passed, all the grandchildren fought over the Breadholder. It’s one of my favorite things from her house.",
    details: ["Cass Shaffer", "Scottville, MI (2023)"],
    scale: 2.5,
    rotation: Math.PI / 4,
    x: 0.82,
    y: 9.86,
    z: -3.36,

    zoomX: 1.64,
    zoomY: 14.16,
    zoomZ: -3.11,
    zoomScale: 1.08,
  },
  {
    path: "/models/iuo/Bunny.glb",
    name: "Mom’s Bunny Salt Shaker",
        cardNum: "#2302",
    poetic:
      "It’s completely cute and I love it. Plus, I wanted to see what it would look like in 3D. ",
    details: ["Nicole Miller", "Bloomington, IN (2023)"],
    scale: 46.97,
    rotation: Math.PI / 4,
    x: 0.66,
    y: 9.24,
    z: -4.17,

    zoomX: 1.4,
    zoomY: 13.24,
    zoomZ: -7.04,
    zoomScale: 1.55,
  },
  {
    path: "/models/sv/TwistFamily.glb",
    name: "Grandma’s Wooden Fish Carving",
            cardNum: "#2303",
    poetic:
      "I like how unique it is, that it looks like someone made it, and that you can hold it in your hand.   ",
    details: ["Twist Paggeot", "Scottville, MI (2023)"],
    scale: 11.56,
    rotation: 5.9,
    x: 1.17,
    y: 11.14,
    z: -1.63,

    zoomX: 1.35,
    zoomY: 13.91,
    zoomZ: -2.9,
    zoomScale: 1.5,
  },
  {
    path: "/models/sv/AlexJewelryBoxRMCOMPRESSED.glb",
    name: "Grandma’s Marble Jewelry Box",
    poetic:
      "She had lots of little keepsakes, but this one had weight and felt important. ",
    details: ["Alex Morlock", "Scottville, MI (2023)"],
    scale: 27.81,
    rotation: Math.PI / 4,
    x: -0.16,
    y: 10.17,
    z: -1.51,

    zoomX: -0.08,
    zoomY: 14.16,
    zoomZ: -5.08,
    zoomScale: 1.8,
  },
  {
    path: "/models/sv/CookieJar.glb",
    name: "Grandma’s Piggy Cookie Jar",
    poetic:
      "This got me into collecting cookie jars. I think it was probably painted, but that’s faded. ",
    details: ["Patti Pitcher", "Grand Haven, MI (2023)"],
    scale: 21.42,
    rotation: Math.PI / 4,
    x: 0.7,
    y: 10.17,
    z: -1.51,

    zoomX: 0.66,
    zoomY: 14.47,
    zoomZ: -3.11,
    zoomScale: 1.55,
  },
  {
    path: "/models/sv/ChesnaCOMPRESSED.glb",
    name: "Grandfather’s Gold Pocket Watch and Fob",
    poetic:
      "It’s literally the coolest thing I own. I should take it out and show it off more.",
    details: ["Chesna Saxton", "Scottville, MI (2023)"],
    scale: 2.26,
    rotation: Math.PI / 4,
    x: -0.62,
    y: 10.17,
    z: -1.51,

    zoomX: -0.33,
    zoomY: 13.24,
    zoomZ: -2.62,
    zoomScale: 1.19,
  },
  {
    path: "/models/sv/DadGrammaWatchRM.glb",
    name: "Grandpa’s Aviator Watch ",
    poetic:
      "My father and grandfather were both jewelers, so I got all the details about this timepiece and what made it unique for the time.  ",
    details: ["Megan Young", "Grand Haven, MI (2023)"],
    scale: 3,
    rotation: Math.PI / 4,
    x: -0.62,
    y: 9.55,
    z: -3.97,

    zoomX: 0.41,
    zoomY: 13.24,
    zoomZ: -9.99,
    zoomScale: 1.69,
  },
  {
    path: "/models/sv/JGPottery.glb",
    name: "Great Grandma’s Floral Ceramic Dish",
    poetic:
      "This was on one of the tables in the sitting room. I love the pattern even though I’m not sure where she got it.",
    details: ["Jonah Goehmann", "Scottville, MI (2023)"],
    scale: 103.56,
    rotation: 1.57,
    x: 0.36,
    y: 10.78,
    z: -5.44,

    zoomX: 1.09,
    zoomY: 15.55,
    zoomZ: -5.95,
    zoomScale: 1.27,
  },
  {
    path: "/models/sv/JesseRaccoon.glb",
    name: "Grandma’s Hide-a-Spare-Key Raccoon ",
    poetic:
      "This little guy sat in the front garden and gramma hid a house key in it in case we ever got locked out.",
    details: ["Jesse Schmidt ", "Scottville, MI (2023)"],
    scale: 40.26,
    rotation: Math.PI / 4,
    x: 0.66,
    y: 10.46,
    z: -4.17,

    zoomX: 1.4,
    zoomY: 15.23,
    zoomZ: -5.57,
    zoomScale: 1.22,
  },
  {
    path: "/models/iuo/DasiyVaseCOMPRESSED.glb",
    name: "Mom's Polyresin Vase",
    poetic:
      "I love to change my decor with the seasons, so this comes out in the fall months. ",
    details: ["Kate Westhoven", "Bloomington, IN (2023)"],
    scale: 19.82,
    rotation: Math.PI / 4,
    x: 0.66,
    y: 9.24,
    z: -1.51,

    zoomX: 0.66,
    zoomY: 12.93,
    zoomZ: -2.62,
    zoomScale: 1.5,
  },
  {
    path: "/models/cle/Teapot.glb",
    name: "Great Grandma’s Play Tea Set",
    poetic:
      "Growing up, I would host tea parties with this tiny set and invite friends over to share.",
    details: ["Alexandria Young", "Cleveland, OH (2023) "],
    scale: 9.36,
    rotation: Math.PI / 4,
    x: 0,
    y: 9.82,
    z: -4.17,

    zoomX: 0.84,
    zoomY: 14.27,
    zoomZ: -8.5,
    zoomScale: 1.5,
  },
  {
    path: "/models/iuo/Wave1COMPRESSED.glb",
    name: "Grandpa’s Shortwave Radio ",
    poetic: "I love the look of this radio, with the dials and readouts. ",
    details: ["Ahmed Ozsever ", "Bloomington, IN (2023)"],
    scale: 20.93,
    rotation: Math.PI / 4,
    x: 0,
    y: 11.09,
    z: -2.9,

    zoomX: 1.09,
    zoomY: 15.7,
    zoomZ: -3.41,
    zoomScale: 1.2,
  },
  {
    path: "/models/sv/GrandpaPin.glb",
    name: "Grandpa’s Military Pin ",
    poetic:
      "My grandfather and great grandfather both served. This reminds me and makes me feel proud of our family. ",
    details: ["Trevor Stimes", "Scottville, MI (2023)"],
    scale: 67.5,
    rotation: Math.PI / 4,
    x: 0.82,
    y: 9.86,
    z: -1.56,

    zoomX: 1.15,
    zoomY: 14.47,
    zoomZ: -0.65,
    zoomScale: 1.26,
  },
  // {
  //   path: "/models/sv/MegGrammaRing.glb",
  //   name: "Meg Gramma Ring",
  //   details: ["Contributor: FIRST NAME LAST NAME", "Scottville, MI (2023)"],
  //   scale: 150,
  //   rotation: Math.PI / 4,
  //   x: 0.66,
  //   y: 9.55,
  //   z: -3.97,

  //   zoomX: 1.4,
  //   zoomY: 13.55,
  //   zoomZ: -6.55,
  //   zoomScale: 1.51,
  // },
  // {
  //   path: "/models/sv/AutumnRingRM.glb",
  //   name: "Grandma Ring",
  //   poetic:
  //     "After my gram passed, all the grandchildren fought over the Breadholder. It’s one of my favorite things from her house.",
  //   details: ["Dyllan Evans", "Scottville, MI (2023)"],
  //   scale: 10.5,
  //   rotation: Math.PI / 4,
  //   x: 0.82,
  //   y: 11.09,
  //   z: -3.36,

  //   zoomX: 0.9,
  //   zoomY: 14.78,
  //   zoomZ: -6.55,
  //   zoomScale: 1.8,
  // },
];
